apiVersion: v1
kind: ConfigMap
metadata:
  name: vpn-config
  namespace: vpn-system
data:
  wg0.conf: |
    [Interface]
    PrivateKey = SERVER_PRIVATE_KEY_PLACEHOLDER
    Address = 10.0.0.1/24
    ListenPort = 51820
    PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

  haproxy.cfg: |
    global
        daemon
        log stdout local0
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 30s
        user haproxy
        group haproxy

    defaults
        mode tcp
        log global
        option tcplog
        option dontlognull
        option redispatch
        retries 3
        timeout connect 5000
        timeout client 50000
        timeout server 50000

    listen stats
        bind *:8404
        stats enable
        stats uri /stats
        stats refresh 5s
        stats admin if TRUE

    frontend vpn_frontend
        bind *:51820
        mode udp
        default_backend vpn_backend

    backend vpn_backend
        mode udp
        balance roundrobin
        option udp-check
        server vpn1 vpn-wireguard:51820 check

    frontend health_check
        bind *:80
        mode http
        http-request return status 200 content-type text/plain string "OK"






